; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
;upload_port = COM[8]
monitor_speed = 115200
board_build.partitions = default.csvplatformio.ini
upload_protocol = espota
upload_port = 192.168.68.108
upload_flags = 
	--auth=admin2
	--port=8266
	--host_port=55910
lib_deps = 
	https://github.com/khoih-prog/RP2040_PWM
	;emelianov/modbus-esp8266@^4.1.0
  	# Libreria fija sin cambios futuros
  	ArduinoOTA @ 1.0
